name: Angular CI workflow

on:
  push:
    branches: [ master ]
  pull-request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out code briefly
    - uses: actions/checkout@v4

    - name: build Node env
      uses: actions/setup-node@v4
      with: 
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: run Lint
      run: npm run lint

    - name: Run Unit Tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    - name: Build Angular App
      run: npm run build -- --configuration=production
        
    

